services:
  - type: web
    name: wise-energy-ukraine-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TOKEN
        value: 7792444465:AAGZ2n-_F6x-c3WtlSWzCVJYC9pzVGQCZWs